name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up python on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build binary
      run: |
        pip install pyinstaller
        pip install .
        pyinstaller wddh.spec
    - name: Upload Windows binary
      if: runner.os == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: wddh.exe
        path: dist/wddh.exe
    - name: Upload non windows binary
      if: runner.os != 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: wddh-${{ matrix.os }}
        path: dist/wddh
